Repository arsenijlevin/zachetka-ru, pull requests merged in 2023-09, with the labels that each got.

#49 PT-136 Добавление недостающих эндпоинтов в API
  src/client/components/pop-ups/AttendanceCheckPopUp.tsx
  src/client/pages/attendance-code/[code].tsx
  src/server/src/attendance/attendance.controller.ts
  src/server/src/attendance/attendance.repository.ts
  src/server/src/attendance/attendance.service.ts
  src/server/src/auth/auth.controller.ts
  src/server/src/auth/auth.service.ts
  src/server/src/lessons/lessons.controller.ts
  src/server/src/lessons/lessons.repository.ts
  src/server/src/lessons/lessons.service.ts
  src/server/src/users/dto/user.dto.ts
  src/server/src/users/users.controller.ts
  src/server/src/users/users.repository.ts
  src/server/src/users/users.service.ts
Labels: enhancement

#50 PT-137 Доработка панели администратора
  package-lock.json
  src/client/components/pop-ups/AddGroupPopUp.tsx
  src/client/components/pop-ups/AddLecturePopUp.tsx
  src/client/components/pop-ups/AddLecturerPopUp.tsx
  src/client/components/pop-ups/AddStudentPopUp.tsx
  src/client/components/pop-ups/AddSubjectPopUp.tsx
  src/client/components/pop-ups/AttendanceCheckPopUp.tsx
  src/client/components/pop-ups/ChangeSubjectPopUp.tsx
  src/client/components/pop-ups/DeleteLecturePopUp.tsx
  src/client/components/pop-ups/DeleteSubjectPopUp.tsx
  src/client/pages/attendance-code/[code].tsx
  src/server/src/attendance/attendance.controller.ts
  src/server/src/attendance/attendance.repository.ts
  src/server/src/attendance/attendance.service.ts
  src/server/src/auth/auth.controller.ts
  src/server/src/auth/auth.service.ts
  src/server/src/lessons/lessons.controller.ts
  src/server/src/lessons/lessons.repository.ts
  src/server/src/lessons/lessons.service.ts
  src/server/src/users/dto/user.dto.ts
  src/server/src/users/users.controller.ts
  src/server/src/users/users.repository.ts
  src/server/src/users/users.service.ts
Labels: enhancement

#51 PT-142 Актуализация информации в курсовой работе
  README.md
  documentation/курсовая работа/Курсовая работа.docx
  documentation/курсовая работа/Курсовая работа.pdf
Labels: documentation

#52 PT-135 Описание проделанной работы в сопроводительном письме
  documentation/сопроводительное письмо/Сопроводительное письмо.docx
  documentation/сопроводительное письмо/Сопроводительное письмо.pdf
Labels: documentation

#53 PT-132 Демонстрационное видео функциональности проекта
  README.md
Labels: documentation

#55 Исправление ошибок eslint. Форматирование
  src/client/components/pop-ups/AddGroupPopUp.tsx
  src/client/components/pop-ups/AddLecturePopUp.tsx
  src/client/components/pop-ups/AddLecturerPopUp.tsx
  src/client/components/pop-ups/AddStudentPopUp.tsx
  src/client/components/pop-ups/AddSubjectPopUp.tsx
  src/client/components/pop-ups/AttendanceCheckPopUp.tsx
  src/client/components/pop-ups/ChangeSubjectPopUp.tsx
  src/client/components/pop-ups/DeleteLecturePopUp.tsx
  src/client/components/pop-ups/DeleteSubjectPopUp.tsx
  src/client/pages/attendance-code/[code].tsx
Labels: bug

#58 Release/1.3.2
  .github/workflows/main.yml
  src/package-lock.json
  src/server/package.json
Labels: bug, enhancement
